providers:
  openai:
    models:
      - gpt-3.5-turbo
      - gpt-4-1106-preview
      - gpt-4o
    parameters:
      temperature: 0
      model_kwargs:
        top_p: 1
        frequency_penalty: 0
        presence_penalty: 0
  databricks:
    models:
      - Llama-2-70B-Chat
      - Meta-Llama-3-70b-Instruct
      - Mixtral-8x7B-Instruct
      - MPT-7B-Instruct
      - MPT-30B-Instruct
      - DBRX-Instruct
    parameters:
      temperature: 0
      max_tokens: null
